addSbtPlugin("io.spray"         % "sbt-revolver"         % "0.10.0")
addSbtPlugin("edu.gemini"       % "sbt-lucuma-lib"       % "0.12.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.6.4")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager"  % "1.10.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "2.1.0")
